# Discovered from CustomResource metadata
name: "{{ meta.name }}"
namespace: "{{ meta.namespace }}"

# Mysql image vars
registry_url: docker-registry.default.svc:5000
mysql_version: "5.7"
image_namespace: openshift

# Openshift service of the mysql deployment
mysql_service: mysql

# Backup capacity
volume_capacity: 1Gi

# Take backup every {{ intervalMinutes }} minutes.
# A value of 0 means only take one backup
interval_minutes: 0

# Max number of backup PVCs to keep (if using a timed backup)
max_backups: 3