- name: database-provision playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: deprovision
  roles:
  - role: database-provision
    